#  Copyright (c) 2023-2026 Carnegie Mellon University.
#  NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE
#  ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS.
#  CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND,
#  EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT
#  NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
#  MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE
#  OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE
#  ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM
#  PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#  Licensed under a MIT (SEI)-style license, please see LICENSE or contact
#  permission@sei.cmu.edu for full terms.
#  [DISTRIBUTION STATEMENT A] This material has been approved for
#  public release and unlimited distribution. Please see Copyright notice
#  for non-US Government use and distribution.
#  This Software includes and/or makes use of Third-Party Software each
#  subject to its own license.
#  DM24-0278
"""The generated data files must not depend on the machine that wrote them.

The decision point descriptions carry curly quotes. Those code points also exist
in the legacy Windows code pages, so writing them without an explicit encoding
succeeds and silently emits non-UTF-8 bytes: no exception, no warning, exit 0.
The pre-commit hook and run_doctools.yml both tell a contributor to regenerate
and push the result, so the corruption reaches the index.
"""
import os
import pathlib
import subprocess
import sys
import tempfile
import unittest

DOCTOOLS = pathlib.Path(__file__).resolve().parents[1] / "ssvc" / "doctools.py"


class DoctoolsEncodingTest(unittest.TestCase):
    def test_generation_never_falls_back_to_the_locale(self):
        """No file written by a full run may be opened without an encoding.

        Run under -X warn_default_encoding (PEP 597), which reports an implicit
        encoding on every platform. Asserting on the generated bytes instead
        would pass on a UTF-8 runner whether or not the defect is present,
        which is why CI has never seen this.

        Only warnings raised from inside this package count: dependencies open
        files without an encoding at import time and would otherwise decide the
        result.
        """
        with tempfile.TemporaryDirectory() as datadir:
            env = dict(os.environ, PYTHONWARNDEFAULTENCODING="1")
            result = subprocess.run(
                [
                    sys.executable,
                    "-X",
                    "warn_default_encoding",
                    str(DOCTOOLS),
                    f"--datadir={datadir}",
                    "--overwrite",
                ],
                capture_output=True,
                env=env,
                timeout=600,
            )

        stderr = result.stderr.decode("utf-8", "replace")
        ours = [
            line
            for line in stderr.splitlines()
            if "EncodingWarning" in line and f"{os.sep}ssvc{os.sep}" in line
        ]
        self.assertEqual(result.returncode, 0, stderr)
        self.assertEqual(ours, [], "\n".join(ours))


if __name__ == "__main__":
    unittest.main()
