#!/usr/bin/env python
"""
Models the CVSS v4.0 Qualitative Severity Ratings from Equivalence Set 1-6
"""
#  Copyright (c) 2025 Carnegie Mellon University.
#  NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE
#  ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS.
#  CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND,
#  EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT
#  NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
#  MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE
#  OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE
#  ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM
#  PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#  Licensed under a MIT (SEI)-style license, please see LICENSE or contact
#  permission@sei.cmu.edu for full terms.
#  [DISTRIBUTION STATEMENT A] This material has been approved for
#  public release and unlimited distribution. Please see Copyright notice
#  for non-US Government use and distribution.
#  This Software includes and/or makes use of Third-Party Software each
#  subject to its own license.
#  DM24-0278
from ssvc.decision_points.cvss.equivalence_set_1 import EQ1
from ssvc.decision_points.cvss.equivalence_set_2 import EQ2
from ssvc.decision_points.cvss.equivalence_set_3 import EQ3
from ssvc.decision_points.cvss.equivalence_set_4 import EQ4
from ssvc.decision_points.cvss.equivalence_set_5 import EQ5
from ssvc.decision_points.cvss.equivalence_set_6 import EQ6
from ssvc.decision_tables.base import DecisionTable
from ssvc.outcomes.cvss.lmhc import LMHC

dp_array = [EQ1, EQ2, EQ3, EQ4, EQ5, EQ6, LMHC]

dp_dict = {dp.id: dp for dp in dp_array}


QSR_4 = DecisionTable(
    name="CVSS v4.0 Qualitative Severity Ratings",
    key="CVSS_QSR",
    version="4.0.0",
    namespace="cvss",
    definition="CVSS v4.0  using MacroVectors and Interpolation. See https://www.first.org/cvss/specification-document#New-Scoring-System-Development for details",
    decision_points=dp_dict,
    outcome=LMHC.id,
    mapping=[
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "L",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "M",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "H",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "L",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "L",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "L",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "L",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "L",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "M",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "M",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "M",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "L",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "M",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
        {
            "cvss:EQ1:1.0.0": "H",
            "cvss:EQ2:1.0.0": "H",
            "cvss:EQ3:1.0.0": "H",
            "cvss:EQ4:1.0.0": "H",
            "cvss:EQ5:1.0.0": "H",
            "cvss:EQ6:1.0.0": "H",
            "cvss:CVSS:1.0.0": "C",
        },
    ],
)

VERSIONS = [
    QSR_4,
]
LATEST = QSR_4


# def corrections():
#     from ssvc.outcomes.cvss._v4expected import V4_EXPECTED
#
#     expected = {}
#     for row in V4_EXPECTED:
#         key = tuple([v for k, v in row.items() if k != QSR_4.outcome])
#         expected[key] = row
#
#     # now go through default mapping and replace expected rows
#     new_mapping = []
#     for row in QSR_4.mapping:
#         new_row = dict(row)
#         key = tuple([v for k, v in row.items() if k != QSR_4.outcome])
#         if key in expected:
#             new_mapping.append(expected[key])
#         else:
#             if row[EQ3.id] == "L" and row[EQ6.id] == "H":
#                 # this combination is not permitted
#                 # so instead we're going to lookup
#                 # the outcome from "3=L, 6=L", all else being equal
#                 new_key = list(key)
#                 new_key[5] = "L"  # EQ6
#                 new_key = tuple(new_key)
#                 if new_key in expected:
#                     new_row[QSR_4.outcome] = expected[new_key][QSR_4.outcome]
#                 else:
#                     raise KeyError(
#                         f"Warning: No expected row for {new_key} in CVSS v4."
#                     )
#             else:
#                 # why are we here?
#                 raise KeyError(f"Warning: No expected row for {key} in CVSS v4.")
#
#             new_mapping.append(new_row)
#     return new_mapping


def main():

    print(QSR_4.model_dump_json(indent=2))

    import pandas as pd

    df = pd.DataFrame(QSR_4.mapping)
    print(df.to_csv(index=False))

    # print(corrections())


if __name__ == "__main__":
    main()
