#!/usr/bin/env python
"""
Provides the Coordination Triage decision table for SSVC."""

#  Copyright (c) 2025 Carnegie Mellon University.
#  NO WARRANTY. THIS CARNEGIE MELLON UNIVERSITY AND SOFTWARE
#  ENGINEERING INSTITUTE MATERIAL IS FURNISHED ON AN "AS-IS" BASIS.
#  CARNEGIE MELLON UNIVERSITY MAKES NO WARRANTIES OF ANY KIND,
#  EITHER EXPRESSED OR IMPLIED, AS TO ANY MATTER INCLUDING, BUT
#  NOT LIMITED TO, WARRANTY OF FITNESS FOR PURPOSE OR
#  MERCHANTABILITY, EXCLUSIVITY, OR RESULTS OBTAINED FROM USE
#  OF THE MATERIAL. CARNEGIE MELLON UNIVERSITY DOES NOT MAKE
#  ANY WARRANTY OF ANY KIND WITH RESPECT TO FREEDOM FROM
#  PATENT, TRADEMARK, OR COPYRIGHT INFRINGEMENT.
#  Licensed under a MIT (SEI)-style license, please see LICENSE or contact
#  permission@sei.cmu.edu for full terms.
#  [DISTRIBUTION STATEMENT A] This material has been approved for
#  public release and unlimited distribution. Please see Copyright notice
#  for non-US Government use and distribution.
#  This Software includes and/or makes use of Third-Party Software each
#  subject to its own license.
#  DM24-0278

from ssvc.decision_points.ssvc.public_safety_impact import (
    PUBLIC_SAFETY_IMPACT_2_0_1 as PublicSafetyImpact,
)
from ssvc.decision_points.ssvc.report_credibility import (
    REPORT_CREDIBILITY_1 as ReportCredibility,
)
from ssvc.decision_points.ssvc.report_public import (
    REPORT_PUBLIC_1 as ReportPublic,
)
from ssvc.decision_points.ssvc.supplier_cardinality import (
    SUPPLIER_CARDINALITY_1 as SupplierCardinality,
)
from ssvc.decision_points.ssvc.supplier_contacted import (
    SUPPLIER_CONTACTED_1 as SupplierContacted,
)
from ssvc.decision_points.ssvc.supplier_engagement import (
    SUPPLIER_ENGAGEMENT_1 as SupplierEngagement,
)
from ssvc.decision_points.ssvc.utility import UTILITY_1_0_1 as Utility
from ssvc.decision_tables.base import DecisionTable
from ssvc.namespaces import NameSpace
from ssvc.outcomes.ssvc.coordinate import COORDINATE_1_0_1 as Outcome

V1_0_0 = DecisionTable(
    namespace=NameSpace.SSVC,
    key="COORD_TRIAGE",
    version="1.0.0",
    name="Coordinator Triage",
    definition="Decision table for coordinator triage",
    decision_points={
        dp.id: dp
        for dp in [
            ReportPublic,
            SupplierContacted,
            ReportCredibility,
            SupplierCardinality,
            SupplierEngagement,
            Utility,
            PublicSafetyImpact,
            Outcome,
        ]
    },
    outcome=Outcome.id,
    mapping=[
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "L",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "T",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "D",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "M",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "E",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "A",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "O",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "NC",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "N",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "Y",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
        {
            "ssvc:RP:1.0.0": "N",
            "ssvc:SCON:1.0.0": "Y",
            "ssvc:RC:1.0.0": "C",
            "ssvc:SC:1.0.0": "M",
            "ssvc:SE:1.0.0": "U",
            "ssvc:U:1.0.1": "S",
            "ssvc:PSI:2.0.1": "S",
            "ssvc:COORDINATE:1.0.1": "C",
        },
    ],
)

VERSIONS = (V1_0_0,)
LATEST = VERSIONS[-1]


def main():
    from ssvc.decision_tables.helpers import print_dt_version

    print_dt_version(LATEST, longform=False)


if __name__ == "__main__":
    main()
