services:
  base:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    image: base:latest

  dependencies:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dependencies
    image: dependencies:latest
    depends_on:
      - base

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    image: test:latest
    depends_on:
      - dependencies

  docs:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: docs
    image: docs:latest
    depends_on:
      - dependencies
    ports:
      - "8000:8000"

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: registry_api
    image: registry_api:latest
    depends_on:
      - dependencies
    ports:
      - "8001:8000"