name: Copy on push to staging

# This workflow copies the staging branch to the staging repository.
# Functional summary:
# on push to staging branch
# or manually triggered
# do
# check out staging branch
# add staging repository as remote
# push to staging repository
on:
  push:
    branches: [staging]
    workflow_dispatch:

env:
  STAGING_REPO: https://github.com/CERTCC/SSVC-staging.git

jobs:
    copy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: staging
      - name: git config
        run: |
          git config --global user.name 'certcc-ghbot'
          git config --global user.email 'cert+ghbot@cert.org'
        shell: bash
      - name: add remote
        run: git remote --verbose add ssvc_staging $STAGING_REPO
      - name: Push to staging repository
        run: git push --verbose ssvc_staging staging
